# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LibraryDismantling' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'anim'
	pod 'Hero'
	pod "Spruce", '~> 1.0.0'
  # Pods for LibraryDismantling

end
